cc_binary(
    name = 'condvar-test',
    srcs = [
        'main.cc'
    ],
    deps = [
        '//toft/system/threading:threading',
        '//toft/system/threading:_this_thread',
        '//toft/system/threading:_thread',
    ],
)
