cc_binary(
  name = 'leveldb_bench',
  srcs = [
    'LevelDBBench.cpp',
  ],
  deps = [
    '//folly:folly',
    '//leveldb:leveldb',
    '//thirdparty/glog:glog',
  ]
)

cc_binary(
  name = 'rocksdb_bench',
  srcs = [
    'RocksDBBench.cpp',
  ],
  deps = [
    '//folly:folly',
    '//rocksdb:rocksdb',
    '//thirdparty/glog:glog',
  ]
)
