cc_binary(
    name = 'bench',
    srcs = [
        'bench.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_binary(
    name = 'client',
    srcs = [
        'client.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_binary(
    name = 'server',
    srcs = [
        'server.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

